apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-probe
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      initContainers:
      - name: check-service
        image: busybox
        command: ['sh', '-c', 'until nslookup nginx-probe.default.svc.cluster.local; do echo "Waiting for nginx-probe service"; sleep 2; done;']
