apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl
  labels:
    app: nginx-ssl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ssl
  template:
    metadata:
      labels:
        app: nginx-ssl
    spec:
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-ssl-config
          items:
          - key: index.html
            path: index.html
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80

