apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mt
  labels:
    app: nginx-mt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-mt
  template:
    metadata:
      labels:
        app: nginx-mt
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:openshift
        ports:
        - containerPort: 1180
