apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-read
  labels:
    app: write-read
spec:
  replicas: 3
  selector:
    matchLabels:
      app: write-read
  template:
    metadata:
      labels:
        app: write-read
    spec:
      volumes:
      - name: vol
        hostPath:
          path: /var/k8s-data
      containers:
      - name: vol-write
        image: busybox
        command: ['sh', '-c', 'i=0; while true; do echo "New line" > /output/file; sleep 5; done']
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: vol-read
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol
          mountPath: /input
