apiVersion: v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: multitool
            port:
              number: 80
