apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/local"
