apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-reader
spec:
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      volumes:
      - name: syslog
        hostPath:
          path: /var/log/syslog
          type: File
      containers:
      - name: log-reader
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
        volumeMounts:
        - name: syslog
          mountPath: /logs/node-syslog
          readOnly: true
